# Generated by Django 4.1.7 on 2023-03-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fathi_djangoregistration', '0004_student_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.IntegerField(default=1),
        ),
    ]
